### ISSUE TITLE
Can't manage the same stanza in multiple files

### ISSUE THREAD

**Issue by ITBlogger** [wcooley/puppet-splunk_conf#2]
Hi,

This module is great and it's already proven itself to be useful within minutes of downloading it.

I have run into one issue with it, however. Since the resource is defined based on the stanza, there's no way for me to define a stanza in two different files.

For instance, if I have a server that has universal forwarder and server both installed at the same time, I can't use this module to modify the web.conf for both the splunk and splunkforwarder directory trees.

Any help would be greatly appreciated.

Thanks,

Alex

**Comment by wcooley** [comment]
Hi Alex,

I've merged your changes with some additions -- `stanza` is optional, defaulting to the resource title, so no one's existing users will need to change.

Thanks for the contribution!
Wil

**Comment by ITBlogger** [comment]
Nice! Wish I had thought of that. :D

Thanks,

Alex
